name: vitalzone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9263470247387886
  lightness: 0.5
  saturation: 0.7361560361459851
  rhythmicContrast: 1
purpose: []
